In [44]:
pip install pandas scikit-learn nltk

Requirement already satisfied: pandas in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (2.3.1)
Requirement already satisfied: scikit-learn in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (1.7.1)
Requirement already satisfied: nltk in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (3.9.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhia\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.3.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\abhia\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\abhia\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
import pandas as pd 

df1 = pd.read_csv("uci", sep="\t", header=None)
df1.columns = ["label", "message"]

print(df1.head())

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [46]:
df2 = pd.read_csv("syn.csv")
df2.columns = ["label", "message"]

print(df2.head())

  label                                            message
0  spam        Pre-approved loan of Rs 10000. Apply today.
1  spam  Reward points worth Rs 5000 expiring immediate...
2  spam  Your account credited with Rs 25000. If not yo...
3  spam  Parcel on hold. Update address urgent at http:...
4  spam           PAN not linked with Aadhaar. Update now.

In [47]:
df= pd.concat([df1, df2])
print(df)

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
9995  spam  KYC incomplete for HDFC. Submit documents with...
9996  spam  RBI alert: Suspicious activity detected. Verif...
9997  spam   Your UPI ID hitesh@upi is suspended. Verify now.
9998  spam  Electricity bill pending of Rs 25000. Pay imme...
9999   ham                                    Dinner at 8 pm?

[15572 rows x 2 columns]

In [48]:
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', '', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['clean_message'] = df['message'].apply(clean_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\abhia\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [49]:
df

,label,message,clean_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think goes usf lives around though
...,...,...,...
9995,spam,KYC incomplete for HDFC. Submit documents with...,kyc incomplete hdfc submit documents within 10...
9996,spam,RBI alert: Suspicious activity detected. Verif...,rbi alert suspicious activity detected verify ...
9997,spam,Your UPI ID hitesh@upi is suspended. Verify now.,upi id hiteshupi suspended verify
9998,spam,Electricity bill pending of Rs 25000. Pay imme...,electricity bill pending rs 25000 pay immediat...
9999,ham,Dinner at 8 pm?,dinner 8 pm

In [50]:
df = df.dropna()
df = df.reset_index(drop=True)

In [51]:
df

,label,message,clean_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think goes usf lives around though
...,...,...,...
15567,spam,KYC incomplete for HDFC. Submit documents with...,kyc incomplete hdfc submit documents within 10...
15568,spam,RBI alert: Suspicious activity detected. Verif...,rbi alert suspicious activity detected verify ...
15569,spam,Your UPI ID hitesh@upi is suspended. Verify now.,upi id hiteshupi suspended verify
15570,spam,Electricity bill pending of Rs 25000. Pay imme...,electricity bill pending rs 25000 pay immediat...
15571,ham,Dinner at 8 pm?,dinner 8 pm

In [52]:
# from sklearn.feature_extraction.text import TfidfVectorizer

# vectorizer = TfidfVectorizer(
#     max_features=800,     
#     ngram_range=(1,2)     
# )

# X = vectorizer.fit_transform(df['clean_message'])

# print(X.shape)

In [53]:
# vectorizer.get_feature_names_out()

In [54]:
# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# y = le.fit_transform(df['label'])  # spam=1, ham=0

In [55]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# X_norm = scaler.fit_transform(X.toarray())

## Feature Engg.

In [56]:
df['label'] = df['label'].map({'ham':0, 'spam':1})

In [79]:
from sklearn.model_selection import train_test_split

X_text = df['clean_message']
y = df['label']

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text,
    y,
    test_size=0.4,
    stratify=y,
    random_state=42
)

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=900,
    ngram_range=(1,3),
    stop_words="english",
    sublinear_tf=True
)

X_train_tfidf = vectorizer.fit_transform(X_train_text)
X_test_tfidf = vectorizer.transform(X_test_text)

In [59]:
X_train_tfidf = X_train_tfidf.toarray()
X_test_tfidf = X_test_tfidf.toarray()

In [60]:
import re

def url_features(text):

    has_url = 1 if re.search(r'(http|www)', text.lower()) else 0

    suspicious_domains = ['.xyz','.top','.click','.gq','.work']
    suspicious = 1 if any(d in text.lower() for d in suspicious_domains) else 0

    shorteners = ['bit.ly','tinyurl','t.co','goo.gl']
    short = 1 if any(s in text.lower() for s in shorteners) else 0

    return [has_url, suspicious, short]

In [61]:
keywords = [
    "otp","verify","bank","account","urgent",
    "click","lottery","reward","winner","prize"
]

def keyword_features(text):

    text = text.lower()

    return [1 if k in text else 0 for k in keywords]

In [62]:
def message_stats(text):

    length = len(text) / 200

    digit_ratio = sum(c.isdigit() for c in text) / max(len(text),1)

    upper_ratio = sum(c.isupper() for c in text) / max(len(text),1)

    exclamation = 1 if "!" in text else 0

    return [length, digit_ratio, upper_ratio, exclamation]

In [63]:
import numpy as np

train_extra = []
test_extra = []

for text in X_train_text:
    train_extra.append(
        url_features(text) +
        keyword_features(text) +
        message_stats(text)
    )

for text in X_test_text:
    test_extra.append(
        url_features(text) +
        keyword_features(text) +
        message_stats(text)
    )

train_extra = np.array(train_extra)
test_extra = np.array(test_extra)

In [64]:
X_train_final = np.hstack([X_train_tfidf, train_extra])
X_test_final = np.hstack([X_test_tfidf, test_extra])

In [65]:
print(X_train_final.shape)

(9343, 917)

In [88]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train_final)
X_test = scaler.transform(X_test_final)

In [89]:
X_train

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.2422051 , 0.79941436, 0.        , ..., 0.03125   , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.07317073, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.11111111, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(9343, 917))

In [90]:
from sklearn.neural_network import MLPClassifier

ann_model = MLPClassifier(
    hidden_layer_sizes=(128, 64),   # 2 hidden layers
    activation='relu',
    solver='adam',
    max_iter=20,
    random_state=42
)
 
ann_model.fit(X_train, y_train)

c:\Users\abhia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=20, random_state=42)

In [91]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

y_pred =ann_model.predict_proba(X_test)[:,1]

y_pred = (y_pred > 0.4).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-score:", f1_score(y_test, y_pred))

print("\nDetailed Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.99357842350297
Precision: 0.9929100870125684
Recall: 0.9941916747337851
F1-score: 0.9935504675910997

Detailed Report:

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3130
           1       0.99      0.99      0.99      3099

    accuracy                           0.99      6229
   macro avg       0.99      0.99      0.99      6229
weighted avg       0.99      0.99      0.99      6229

In [92]:
total_params = 0

for coef, intercept in zip(ann_model.coefs_, ann_model.intercepts_):
    total_params += coef.size      # weights
    total_params += intercept.size # bias

print("Total ANN Parameters:", total_params)

Total ANN Parameters: 125825

## SnnTorch

In [93]:
pip install torch snntorch

Requirement already satisfied: torch in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (2.6.0+cu124)
Requirement already satisfied: snntorch in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (0.9.4)
Requirement already satisfied: filelock in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (4.14.1)
Requirement already satisfied: networkx in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (2025.9.0)
Requirement already satisfied: setuptools in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\abhia\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [95]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# Convert train/test data to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

# Create datasets
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

# Create dataloaders
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [96]:
def latency_encoding(x, T=10):
    """
    x: (batch, features)
    returns: (T, batch, features)
    """
    batch_size, num_features = x.shape
    
    spike_times = (T * (1 - x)).long()   # compute spike time
    
    spikes = torch.zeros(T, batch_size, num_features)
    
    for t in range(T):
        spikes[t] = (spike_times == t).float()
        
    return spikes

In [97]:
import torch
import torch.nn as nn
import snntorch as snn
from snntorch import surrogate

beta = 0.9
spike_grad = surrogate.fast_sigmoid()

class SNNModel(nn.Module):

    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()

        self.fc1 = nn.Linear(input_size, hidden_size)
        self.lif1 = snn.Leaky(beta=beta, spike_grad=spike_grad)

        self.fc2 = nn.Linear(hidden_size, output_size)
        self.lif2 = snn.Leaky(beta=beta, spike_grad=spike_grad)

    def forward(self, x):

        mem1 = self.lif1.init_leaky()
        mem2 = self.lif2.init_leaky()

        spk2_rec = []

        num_steps = x.size(0)

        for step in range(num_steps):

            cur1 = self.fc1(x[step])
            spk1, mem1 = self.lif1(cur1, mem1)

            cur2 = self.fc2(spk1)
            spk2, mem2 = self.lif2(cur2, mem2)

            spk2_rec.append(spk2)

        return torch.stack(spk2_rec)

In [98]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

input_size = 917

model = SNNModel(
    input_size=input_size,
    hidden_size=256,
    output_size=2
).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [99]:
num_epochs = 12
T = 50

for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    
    for data, targets in train_loader:
        data = data.to(device)
        targets = targets.to(device)
        
        spikes = latency_encoding(data, T).to(device)
        
        optimizer.zero_grad()
        
        outputs = model(spikes)
        
        # sum spikes over time
        outputs = outputs.sum(dim=0)
        
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(train_loader):.4f}")

Epoch 1, Loss: 0.4482
Epoch 2, Loss: 0.0350
Epoch 3, Loss: 0.0234
Epoch 4, Loss: 0.0183
Epoch 5, Loss: 0.0188
Epoch 6, Loss: 0.0167
Epoch 7, Loss: 0.0163
Epoch 8, Loss: 0.0132
Epoch 9, Loss: 0.0126
Epoch 10, Loss: 0.0125
Epoch 11, Loss: 0.0105
Epoch 12, Loss: 0.0116

In [100]:
from sklearn.metrics import classification_report

model.eval()
all_preds = []
all_targets = []

with torch.no_grad():
    for data, targets in test_loader:
        data = data.to(device)
        targets = targets.to(device)
        
        spikes = latency_encoding(data, T).to(device)
        outputs = model(spikes)
        outputs = outputs.sum(dim=0)
        
        preds = torch.argmax(outputs, dim=1)
        
        all_preds.extend(preds.cpu().numpy())
        all_targets.extend(targets.cpu().numpy())

print(classification_report(all_targets, all_preds))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3130
           1       0.99      0.99      0.99      3099

    accuracy                           0.99      6229
   macro avg       0.99      0.99      0.99      6229
weighted avg       0.99      0.99      0.99      6229

In [101]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

model.eval()
all_preds = []
all_targets = []

with torch.no_grad():
    for data, targets in test_loader:
        data = data.to(device)
        targets = targets.to(device)

        spikes = latency_encoding(data, T).to(device)
        outputs = model(spikes)
        outputs = outputs.sum(dim=0)

        preds = torch.argmax(outputs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_targets.extend(targets.cpu().numpy())

# Convert to numpy
all_preds = np.array(all_preds)
all_targets = np.array(all_targets)

# Metrics
print("Accuracy:", accuracy_score(all_targets, all_preds))
print("Precision:", precision_score(all_targets, all_preds))
print("Recall:", recall_score(all_targets, all_preds))
print("F1-score:", f1_score(all_targets, all_preds))

print("\nDetailed Report:\n")
print(classification_report(all_targets, all_preds))

Accuracy: 0.9908492534917323
Precision: 0.9884393063583815
Recall: 0.9932236205227493
F1-score: 0.9908256880733946

Detailed Report:

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3130
           1       0.99      0.99      0.99      3099

    accuracy                           0.99      6229
   macro avg       0.99      0.99      0.99      6229
weighted avg       0.99      0.99      0.99      6229

In [102]:
print("----- MODEL COMPARISON -----")
print("ANN F1  : 0.9899717150938545 ")
print("SNN F1  :", f1_score(all_targets, all_preds))

----- MODEL COMPARISON -----
ANN F1  : 0.9899717150938545
SNN F1  : 0.9908256880733946

In [103]:
# Evaluate on training set
model.eval()
train_preds = []
train_targets = []

with torch.no_grad():
    for data, targets in train_loader:
        data = data.to(device)
        targets = targets.to(device)
        
        spikes = latency_encoding(data, T).to(device)
        outputs = model(spikes)
        outputs = outputs.sum(dim=0)
        
        preds = torch.argmax(outputs, dim=1)
        
        train_preds.extend(preds.cpu().numpy())
        train_targets.extend(targets.cpu().numpy())

print("Train F1:", f1_score(train_targets, train_preds))

Train F1: 0.9957072333118695

In [104]:
total_params = sum(p.numel() for p in model.parameters())
print("Total Parameters:", total_params)

Total Parameters: 235522

In [ ]:
# torch.save(model.state_dict(), "snn_spam_model.pth")

FileNotFoundError: [Errno 2] No such file or directory: 'snn_spam_model.pth'

In [ ]:
import joblib

joblib.dump(vectorizer, "vectorizer.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']